apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-169641330
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-169641330
    app.kubernetes.io/part-of: test-app-169641330
  name: java-quarkus-169641330
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-169641330
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-169641330
    spec:
      containers:
      - image: quay.io/hacdev/u22fl8du-tenant/test-app-169641330/java-quarkus-169641330@sha256:e9ae5940319d1201bedf99d200ec0a6364945ae82fd0e182ad9f147e6789a9aa
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
