apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: java-quarkus-169641330
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/hacdev/u22fl8du-tenant/test-app-169641330/java-quarkus-169641330@sha256:e9ae5940319d1201bedf99d200ec0a6364945ae82fd0e182ad9f147e6789a9aa
        name: my-java-quarkus
        resources: {}
status: {}
